### ISSUE TITLE
nose 0.11.1 fails to build with Python 2.7

### ISSUE THREAD

**Issue by jpellerin** [nose-devs/nose#141]
nose 0.11.1 fails to build with Python 2.7. (It builds correctly with
Python 2.6.)
# python2.7 setup.py build

Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from nose import **version** as VERSION
  File "/tmp/nose-0.11.1/nose/**init**.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/tmp/nose-0.11.1/nose/core.py", line 15, in <module>
    from nose.result import TextTestResult
  File "/tmp/nose-0.11.1/nose/result.py", line 12, in <module>
    from unittest import _TextTestResult
ImportError: cannot import name _TextTestResult

Google Code Info:
Issue #: 305
Author: Arfrever...@gmail.com
Created On: 2009-11-07T20:43:08.000Z
Closed On: 2009-12-02T23:05:33.000Z
