### ISSUE TITLE
nose doesn't work with jython 2.7 without modification

### ISSUE THREAD

**Issue by drush21** [nose-devs/nose#678]
Whenever I download nose through pip, and try to import it for use in my jython environment I get the issue listed below

> > > import nose
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Jython\Lib\site-packages\nose-1.3.0-py2.7.egg\nose__init__.py", line 1, in <module>
> > >     from nose.core import collector, main, run, run_exit, runmodule
> > >   File "C:\Jython\Lib\site-packages\nose-1.3.0-py2.7.egg\nose\core.py", line 11, in <module>
> > >     from nose.config import Config, all_config_files
> > >   File "C:\Jython\Lib\site-packages\nose-1.3.0-py2.7.egg\nose\config.py", line 9, in <module>
> > >     from nose.plugins.manager import NoPlugins
> > >   File "C:\Jython\Lib\site-packages\nose-1.3.0-py2.7.egg\nose\plugins__init__.py", line 186, in <module>
> > >     from nose.plugins.plugintest import PluginTester
> > >   File "C:\Jython\Lib\site-packages\nose-1.3.0-py2.7.egg\nose\plugins\plugintest.py", line 109, in <module>
> > >     from os import getpid
> > > ImportError: cannot import name getpid

This can be fixed by commenting out lines 109 - 179 of nose.plugins.plugintest.py, which calls the getpid function.
